// Constants for Group Entity
export const GROUP_CONSTANTS = {
   MAX_EXTRA_INFO_LENGTH: 700,
   MIN_EXTRA_INFO_LENGTH: 5,
   MAX_NAME_LENGTH: 60,
   MIN_NAME_LENGTH: 5,
   MAX_INDUSTRY_COUNT: 3,
   MAX_TARGET_COUNTRY_COUNT: 10,
   MAX_TARGET_UNIVERSITY_COUNT: 10,
   MAX_TARGET_FIELD_OF_STUDY_COUNT: 5,
}
