export const universityCountriesMap = {
   CH: "Switzerland",
   AT: "Austria",
   US: "United States",
   DE: "Germany",
   ES: "Spain",
   FI: "Finland",
   FR: "France",
   GB: "United Kingdom",
   IT: "Italy",
   NL: "Netherlands",
   NO: "Norway",
   SE: "Sweden",
   OTHER: "Other",
   "": "None",
   // New
   BE: "Belgium",
   IE: "Ireland",
   BG: "Bulgaria",
   EE: "Estonia",
   HU: "Hungary",
   PL: "Poland",
   PT: "Portugal",
   SK: "Slovakia",
   SI: "Slovenia",
   // Newer
   CA: "Canada",
   IN: "India",
   AF: "Afghanistan",
   AL: "Albania",
   DZ: "Algeria",
   AD: "Andorra",
   AO: "Angola",
   AG: "Antigua and Barbuda",
   AR: "Argentina",
   AM: "Armenia",
   AU: "Australia",
   AZ: "Azerbaijan",
   BS: "Bahamas",
   BH: "Bahrain",
   BD: "Bangladesh",
   BB: "Barbados",
   BY: "Belarus",
   BZ: "Belize",
   BJ: "Benin",
   BM: "Bermuda",
   BT: "Bhutan",
   BO: "Bolivia, Plurinational State of",
   BA: "Bosnia and Herzegovina",
   BW: "Botswana",
   BR: "Brazil",
   BN: "Brunei Darussalam",
   BF: "Burkina Faso",
   MM: "Myanmar",
   BI: "Burundi",
   KH: "Cambodia",
   CM: "Cameroon",
   CV: "Cape Verde",
   KY: "Cayman Islands",
   CF: "Central African Republic",
   TD: "Chad",
   CL: "Chile",
   CN: "China",
   CO: "Colombia",
   CD: "Congo, the Democratic Republic of the",
   CG: "Congo",
   CR: "Costa Rica",
   CI: "Côte d'Ivoire",
   IR: "Iran",
   HR: "Croatia",
   CU: "Cuba",
   CY: "Cyprus",
   CZ: "Czech Republic",
   DK: "Denmark",
   DJ: "Djibouti",
   DM: "Dominica",
   DO: "Dominican Republic",
   EC: "Ecuador",
   EG: "Egypt",
   SV: "El Salvador",
   GQ: "Equatorial Guinea",
   ER: "Eritrea",
   ET: "Ethiopia",
   FO: "Faroe Islands",
   FJ: "Fiji",
   GF: "French Guiana",
   PF: "French Polynesia",
   GA: "Gabon",
   GM: "Gambia",
   GE: "Georgia",
   GH: "Ghana",
   GR: "Greece",
   GL: "Greenland",
   GD: "Grenada",
   GP: "Guadeloupe",
   GU: "Guam",
   GT: "Guatemala",
   GN: "Guinea",
   GY: "Guyana",
   HT: "Haiti",
   VA: "Holy See (Vatican City State)",
   HN: "Honduras",
   HK: "Hong Kong",
   IS: "Iceland",
   ID: "Indonesia",
   IQ: "Iraq",
   IL: "Israel",
   JM: "Jamaica",
   JP: "Japan",
   JO: "Jordan",
   KZ: "Kazakhstan",
   KE: "Kenya",
   KP: "Korea, Democratic People's Republic of",
   KR: "Korea, Republic of",
   XK: "Kosovo",
   KW: "Kuwait",
   KG: "Kyrgyzstan",
   LA: "Lao People's Democratic Republic",
   LV: "Latvia",
   LB: "Lebanon",
   LS: "Lesotho",
   LR: "Liberia",
   LY: "Libya",
   LI: "Liechtenstein",
   LT: "Lithuania",
   LU: "Luxembourg",
   MO: "Macao",
   MK: "North Macedonia",
   MG: "Madagascar",
   MW: "Malawi",
   MY: "Malaysia",
   MV: "Maldives",
   ML: "Mali",
   MT: "Malta",
   MQ: "Martinique",
   MR: "Mauritania",
   MU: "Mauritius",
   MX: "Mexico",
   MD: "Moldova, Republic of",
   MC: "Monaco",
   MN: "Mongolia",
   ME: "Montenegro",
   MS: "Montserrat",
   MA: "Morocco",
   MZ: "Mozambique",
   NA: "Namibia",
   NP: "Nepal",
   NC: "New Caledonia",
   NZ: "New Zealand",
   NI: "Nicaragua",
   NE: "Niger",
   NG: "Nigeria",
   NU: "Niue",
   OM: "Oman",
   PK: "Pakistan",
   PS: "Palestine, State of",
   PA: "Panama",
   PG: "Papua New Guinea",
   PY: "Paraguay",
   PE: "Peru",
   PH: "Philippines",
   PR: "Puerto Rico",
   QA: "Qatar",
   RE: "Réunion",
   RO: "Romania",
   RU: "Russian Federation",
   RW: "Rwanda",
   KN: "Saint Kitts and Nevis",
   LC: "Saint Lucia",
   VC: "Saint Vincent and the Grenadines",
   WS: "Samoa",
   SM: "San Marino",
   SA: "Saudi Arabia",
   SN: "Senegal",
   RS: "Serbia",
   SC: "Seychelles",
   SL: "Sierra Leone",
   SG: "Singapore",
   SB: "Solomon Islands",
   SO: "Somalia",
   ZA: "South Africa",
   SS: "South Sudan",
   LK: "Sri Lanka",
   SD: "Sudan",
   SR: "Suriname",
   SZ: "Swaziland",
   SY: "Syrian Arab Republic",
   TW: "Taiwan",
   TJ: "Tajikistan",
   TZ: "Tanzania, United Republic of",
   TH: "Thailand",
   TG: "Togo",
   TO: "Tonga",
   TT: "Trinidad and Tobago",
   TN: "Tunisia",
   TR: "Turkey",
   TM: "Turkmenistan",
   TC: "Turks and Caicos Islands",
   UG: "Uganda",
   UA: "Ukraine",
   AE: "United Arab Emirates",
   UY: "Uruguay",
   UZ: "Uzbekistan",
   VE: "Venezuela, Bolivarian Republic of",
   VN: "Viet Nam",
   VG: "Virgin Islands, British",
   YE: "Yemen",
   ZM: "Zambia",
   ZW: "Zimbabwe",
}

export const universityCountries = Object.keys(universityCountriesMap)
   .map((key) => ({
      code: key,
      name: universityCountriesMap[key],
   }))
   .filter(({ code }) => code)

export const countryOptions = Object.keys(universityCountriesMap).map(
   (key) => ({
      id: key,
      name: universityCountriesMap[key],
   })
)
