FROM mcr.microsoft.com/playwright:v1.39.0-jammy

COPY ../../. /app

ENV CI=true

# install java for the emulators
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get -y install default-jre-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN npm install
RUN npx playwright install

ENV NODE_ENV test
RUN npm run build

ENTRYPOINT ["npm", "run", "test:e2e-webapp"]