FROM mcr.microsoft.com/playwright:v1.20.0-focal

COPY ../../. /app

# install java for the emulators
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get -y install default-jre-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN npm install

ENTRYPOINT ["npm", "run", "test:e2e-webapp"]