export const AGORA_RTC_CONNECTION_STATE_DISCONNECTED = "DISCONNECTED"
export const AGORA_RTC_CONNECTION_STATE_CONNECTING = "CONNECTING"
export const AGORA_RTC_CONNECTION_STATE_CONNECTED = "CONNECTED"
export const AGORA_RTC_CONNECTION_STATE_RECONNECTING = "RECONNECTING"
export const AGORA_RTC_CONNECTION_STATE_DISCONNECTING = "DISCONNECTING"

// Trigger CI tests
