export const MINIMUM_STREAM_DURATION_MINUTES = 15
export const MAXIMUM_STREAM_DURATION_MINUTES = 180
export const DEFAULT_STREAM_DURATION_MINUTES = 60
export const STREAM_ELEMENT_BORDER_RADIUS = 4
export const STREAM_ELEMENT_SPACING = 0.5
export const LEFT_MENU_WIDTH = 320
export const MAX_STREAM_CHAT_ENTRIES = 100
export const RTC_CLIENT_JOIN_TIME_LIMIT = 10000
export const RTC_CLIENT_RECONNECT_LIMIT = 12000
export const MAX_STREAM_DEFAULT_ACTIVE_HAND_RAISERS = 5

// SpeakerInfoDetails profile icon animation
export const ANIMATE_PROFILE_ICON_AFTER_MS = 10000
