export const MINIMUM_STREAM_DURATION_MINUTES = 15;
export const MAXIMUM_STREAM_DURATION_MINUTES = 180;
export const DEFAULT_STREAM_DURATION_MINUTES = 60;
export const STREAM_ELEMENT_BORDER_RADIUS = 4
export const STREAM_ELEMENT_SPACING = 1

