const allProjectCollectionIds = [
   "activities",
   "admins",
   "analytics",
   "ats",
   "atsRelations",
   "breakoutRooms",
   "breakoutRoomsSettings",
   "callToActions",
   "careerCenterData",
   "chatEntries",
   "comments",
   "companiesUserFollows",
   "companyPageViews",
   "creators",
   "deletedSparks",
   "deletedUsers",
   "detailPageViews",
   "draftLivestreams",
   "fieldsOfStudy",
   "filterGroups",
   "flags",
   "groupAdmins",
   "groupDashboardInvites",
   "groupQuestions",
   "handRaises",
   "highlights",
   "icons",
   "impressions",
   "interests",
   "invites",
   "jobApplications",
   "levelsOfStudy",
   "likedSparks",
   "liveSpeakers",
   "livestreamReferrals",
   "livestreams",
   "marketingUsers",
   "nonVoters",
   "notifications",
   "participatingStats",
   "periods",
   "polls",
   "popularityEvents",
   "preferences",
   "presentations",
   "promotions",
   "questions",
   "rating",
   "ratings",
   "recommendedEvents",
   "recordingStats",
   "recordingStatsUser",
   "recordingToken",
   "registeredGroups",
   "rewards",
   "roles",
   "savedRecruiters",
   "seenSparks",
   "sparks",
   "sparksFeed",
   "sparksFeedMetrics",
   "sparksNotifications",
   "sparkStats",
   "speakers",
   "stats",
   "talentProfiles",
   "timelineCountries",
   "timelineUniversities",
   "tokens",
   "universitiesByCountry",
   "userAdminGroups",
   "userData",
   "userGroups",
   "userInterface",
   "userLivestreamData",
   "userReminders",
   "users",
   "usersInPolicy",
   "usersWhoClicked",
   "usersWhoClickedLink",
   "usersWhoDismissed",
   "videos",
   "voters",
   "wishes",
   "wishList",
] as const

type ProjectCollectionId = (typeof allProjectCollectionIds)[number]

const excludeFromEmulatorCollectionIds: ProjectCollectionId[] = [
   "activities",
   "callToActions",
   "chatEntries",
   "companiesUserFollows",
   "companyPageViews",
   "creators",
   "deletedSparks",
   "deletedUsers",
   "detailPageViews",
   "flags",
   "icons",
   "impressions",
   "invites",
   "likedSparks",
   "periods",
   "popularityEvents",
   "recordingStatsUser",
   "savedRecruiters",
   "seenSparks",
   "sparksFeed",
   "sparksFeedMetrics",
   "sparkStats",
   "talentProfiles",
   "timelineCountries",
   "timelineUniversities",
   "users",
   "usersInPolicy",
   "usersWhoClickedLink",
]

const exludeFromBackupCollectionIds: ProjectCollectionId[] = ["impressions"]

export const collectionsForEmulatorImport = allProjectCollectionIds.filter(
   (id) => !excludeFromEmulatorCollectionIds.includes(id)
)

export const collectionsForBackup = allProjectCollectionIds.filter(
   (id) => !exludeFromBackupCollectionIds.includes(id)
)
