export const UPCOMING_STREAM_THRESHOLD_MINUTES = 45
export const UPCOMING_STREAM_THRESHOLD_MILLISECONDS =
   UPCOMING_STREAM_THRESHOLD_MINUTES * 60 * 1000

export const UPCOMING_STREAM_GRACE_PERIOD_MINUTES = 90
export const UPCOMING_STREAM_GRACE_PERIOD_MILLISECONDS =
   UPCOMING_STREAM_GRACE_PERIOD_MINUTES * 60 * 1000

/**
 * The number of milliseconds to auto-playing a livestream video
 */
export const SECONDS_TO_AUTO_PLAY_LIVESTREAM = 20000
