export const AnalyticsEvents = {
   LivestreamJobOpen: "livestream_job_open",
   LivestreamJobApplicationComplete: "livestream_job_application_complete",
   LivestreamSpeakerLinkedinClick: "livestream_speaker_linkedin_click",
   LivestreamViewerHandRaiser: "livestream_viewer_hand_raiser",
   LivestreamViewerSelectJobs: "livestream_viewer_select_jobs",
   EventAddToCalendar: "event_add_to_calendar",
   EventRegistrationComplete: "event_registration_complete",
   EventRegistrationQuestionSubmit: "event_registration_question_submit",
   EventRegistrationRemoved: "event_registration_removed",
   EventRegistrationStarted: "event_registration_started",
   EventRegistrationStartedFromFooterButton:
      "event_registration_started_from_footer_button",
   EventRegistrationStartedLoginRequired:
      "event_registration_started_login_required",
   EventRegistrationStartedProfileIncomplete:
      "event_registration_started_profile_incomplete",
   EventRegistrationTalentpoolJoin: "event_registration_talentpool_join",
   EventRegistrationTalentpoolSkip: "event_registration_talentpool_skip",
   NewsletterAcceptedOn1stReminder: "newsletter_accepted_on_1st_reminder",
   NewsletterAcceptedOn2ndReminder: "newsletter_accepted_on_2nd_reminder",
   NewsletterAcceptedOnSignup: "newsletter_accepted_on_signup",
   NewsletterDeniedOn1stReminder: "newsletter_denied_on_1st_reminder",
   NewsletterDeniedOn2ndReminder: "newsletter_denied_on_2nd_reminder",
   NewsletterDeniedOnSignup: "newsletter_denied_on_signup",
   SignupCredentialsCompleted: "signup_credentials_completed",
   SignupPinComplete: "signup_pin_complete",
   SignupStarted: "signup_started",
   AttendEvent: "attend_event",
   CompanyPageVisit: "company_page_visit",
   MentorPageVisit: "mentor_page_visit",
   CompanyFollow: "company_follow",
   NewsletterAcceptedOnCompanyPage: "newsletter_accepted_on_company_page",
   RecommendedEventImpression: "recommended_event_impression",
   TalentPoolJoined: "talent_pool_joined",
   TalentPoolLeave: "talent_pool_leave",
   TalentPoolJoinLogin: "talent_pool_join_login",
   SparkClickCompanyPageCTA: "spark_click_company_page_cta",
   SparkClickDiscoverEventCTA: "spark_click_discover_event_cta",
   SparkClickJobCTA: "spark_click_job_cta",
   SparkClickMentorPageCTA: "spark_click_mentor_page_cta",
   SparkClickReachOutLinkedIn: "spark_click_reach_out_linkedin",
   SparkFeedImpression: "spark_feed_impression",
   SparkLike: "spark_like",
   SparkUnlike: "spark_unlike",
   SparkPlayed: "spark_played",
   SparkRegisterEvent: "spark_register_event",
   SparkShareClipboard: "spark_share_clipboard",
   SparkShareFacebook: "spark_share_facebook",
   SparkShareLinkedIn: "spark_share_linkedin",
   SparkShareMobile: "spark_share_mobile",
   SparkShareEmail: "spark_share_email",
   SparkShareOther: "spark_share_other",
   SparkShareWhatsApp: "spark_share_whatsapp",
   SparkShareX: "spark_share_x",
   SparkWatchedComplete: "spark_watched_complete",
   LevelsStart: "levels_start",
   LevelsComplete: "levels_complete",
   LevelsFeedbackRatingSubmitted: "levels_feedback_rating_submitted",
   LevelsFeedbackSurveySubmitted: "levels_feedback_survey_submitted",
   LevelsProgressArticle: "levels_progress_article",
   LevelsProgressHighlight: "levels_progress_highlight",
   LevelsProgressQuiz: "levels_progress_quiz",
   LevelsProgressVideo: "levels_progress_video",
   LevelsLeave: "levels_leave",
   LevelsLivestreamOpened: "levels_livestream_opened",
   LevelsLivestreamRegistrationCompleted:
      "levels_livestream_registration_completed",
   LevelsJobViewed: "levels_job_viewed",
   LevelsJobApplied: "levels_job_applied",
   LevelsMentorView: "levels_mentor_view",
   LevelsMentorLinkedinClick: "levels_mentor_linkedin_click",
   LivestreamOpenSupport: "livestream_open_support",
   LivestreamSpeakerSave: "livestream_speaker_save",
   LivestreamChatNewMessage: "livestream_chat_new_message",
   LivestreamChatOpen: "livestream_chat_open",
} as const

export type AnalyticsEvent =
   (typeof AnalyticsEvents)[keyof typeof AnalyticsEvents]
