import { sxStyles } from "types/commonTypes"

export default sxStyles({
   section: {
      display: "flex",
      alignItems: "flex-start",
      gap: "16px",
      alignSelf: "stretch",
      paddingY: 2,
      fontFamily: "Poppins",
      flexDirection: "row",
      width: "fit-content",
      ":child": {
         flexGrow: 1,
      },
      h3: {
         color: "#2C2C2C",
         fontSize: "24px",
         fontweight: "600",
         margin: "0px",
      },
      h4: {
         color: "#2C2C2C",
         marginY: "6px",
         fontFamily: "Poppins",
         fontSize: "18px",
         fontWeight: 500,
      },
      p: {
         color: "#5F5F5F",
         fontSize: "16px",
         fontWeight: "400",
      },
      h5: {
         color: "#5F5F5F",
         fontSize: "16px",
         fontWeight: 400,
      },
      companyLogoUploadButton: {
         width: "140px",
         height: "140px",
         flexShrink: 0,
         borderRadius: "91px",
         border: "1px solid var(--tertiary-e, #EDE7FD)",
         background: "#F7F8FC",
         display: "flex",
         flexDirection: "column",
         justifyContent: "center",
         alignItems: "center",
         marginY: "10px",
         svg: {
            color: "#9999B1",
            width: "36px",
            height: "36px",
         },
      },
      companyBannerUploadArea: {
         display: "flex",
         flexDirection: "column",
         justifyContent: "center",
         alignItems: "center",
         gap: "12px",
         width: "620px",
         height: "124px",
         flexShrink: 0,
         borderRadius: "4px",
         border: "1px solid var(--tertiary-e, #EDE7FD)",
         background: "#F7F8FC",
         marginY: "10px",
      },
      companyBannerUploadButton: {
         display: "flex",
         padding: "8px 16px",
         justifyContent: "center",
         alignItems: "center",
         gap: "8px",
         borderRadius: "53px",
         border: "1px solid #6749EA",
         color: "#6749EA",
         svg: {
            width: "18px",
            height: "18px",
         },
         caption: {
            leadingTrim: "both",
            textEdge: "cap",
            fontSize: "14px",
            fontWeight: 400,
            lineHeight: "150%",
            letterSpacing: "-0.154px",
         },
      },
      caption: {
         color: "#9999B1",
         textAlign: "center",
         fontSize: "12px",
         fontWeight: 400,
         lineHeight: "141%",
      },
   },
})
