export const RECOMMENDATION_POINTS = {
   // These values are isolated, as in the current design they are not needed
   POINTS_PER_INTEREST_MATCH: 3,
   POINTS_PER_COMPANY_INDUSTRY_MATCH: 2,
   POINTS_PER_COMPANY_SIZE_MATCH: 1,

   /** These values are in the same order as provided in the Figma design as to be easier to match the points system.
    * Example:
      - 5 points if live stream TargetCountry matches
      - 3 points if live stream ...
    */
   POINTS_PER_UNIVERSITY_COUNTRY_MATCH: 10,
   POINTS_PER_TARGET_UNIVERSITY_NAME_MATCH: 5,
   POINTS_PER_FIELD_OF_STUDY_MATCH: 3,
   POINTS_PER_TARGET_LEVEL_OF_STUDY_MATCH: 2,
   POINTS_PER_SPOKEN_LANGUAGE_MATCH: 15,
   POINTS_PER_SPOKEN_LANGUAGE_DEDUCT: 10,
   POINTS_PER_COMPANY_MATCH: 10,
   POINTS_PER_COMPANY_TARGET_COUNTRY_MATCH: 4,
   POINTS_PER_COUNTRY_OF_INTEREST_MATCH: 1,
   POINTS_PER_COMPANY_TARGET_UNIVERSITIES_MATCH: 2,
   POINTS_PER_COMPANY_TARGET_FIELDS_OF_STUDY_MATCH: 3,
   POINTS_PER_CONTENT_TOPIC_TAG_MATCH: 4,
   POINTS_PER_BUSINESS_FUNCTION_TAG_MATCH: 3,

   // Initial points calculation
   POINTS_IF_JOBS_LINKED: 10,
   POPULARITY_NUMERATOR: 1000,
   MAX_POPULARITY_POINTS: 10,

   // Implicit points data
   IMPLICIT: {
      POINTS_PER_INTERACTED_EVENT_COMPANY_COUNTRY_MATCH: 4,
      POINTS_PER_INTERACTED_EVENT_COMPANY_INDUSTRY_MATCH: 2,
      POINTS_PER_INTERACTED_EVENT_COMPANY_SIZE_MATCH: 1,
      POINTS_PER_INTERACTED_EVENT_COMPANY_INTERESTS_MATCH: 3,
      POINTS_PER_INTERACTED_EVENT_COMPANY_LANGUAGE_MATCH: 7,
      POINTS_PER_INTERACTED_EVENT_COMPANY_LANGUAGE_DEDUCT: 3,
      POINTS_PER_WATCHED_SPARKS_COMPANY_COUNTRY_MATCH: 2,
      POINTS_PER_WATCHED_SPARKS_COMPANY_INDUSTRY_MATCH: 4,
      POINTS_PER_WATCHED_SPARKS_COMPANY_SIZE_MATCH: 1,
      POINTS_PER_APPLIED_JOB_COMPANY_COUNTRY_MATCH: 2,
      POINTS_PER_APPLIED_JOB_COMPANY_INDUSTRY_MATCH: 4,
      POINTS_PER_APPLIED_JOB_COMPANY_SIZE_MATCH: 1,
   },

   // Reference livestream recommendation points
   REFERENCE: {
      // Priority 1: Matching industry AND matching location
      INDUSTRY_AND_LOCATION_MATCH_POINTS: 10000,
      // Priority 2: Matching industry BUT different location
      INDUSTRY_MATCH_ONLY_POINTS: 7000,
   },

   // Multiplies live stream points if the user is in the featured group target (implies live stream is from a featured group)
   FEATURED_GROUP_LIVESTREAM_POINTS_MULTIPLIER: 1.25,
} as const
